package com.quiz;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class InsertQuestions {
    public static void getInsertQuestions() throws SQLException, ClassNotFoundException {
        String sql = "insert into mcq(Questions,Answers)values"
                + "('Modern Indo-Aryan languages are based on an ancient language called\r\n"
                + "A. Hindi\r\n"
                + "B. Sanskrit\r\n"
                + "C. Kannada\r\n"
                + "D.Tamil','B'),"
                + "('The Central Command of Army is located at\r\n"
                + "A. Pune\r\n"
                + "B. Udhampur\r\n"
                + "C. Lucknow\r\n"
                + "D. Mhow','C'),"
                + "('The department of Atomic Energy was established in\r\n"
                + "A. 1948\r\n"
                + "B. 1954\r\n"
                + "C. 1963\r\n"
                + "D. 1971','B'),"
                + "('The blood pressure of a young male human being is\r\n"
                + "A. 110/70\r\n"
                + "B. 120/80\r\n"
                + "C. 135/90\r\n"
                + "D. 140/100','B'),"
                + "('The college of Military Engineering is situated at\r\n"
                + "A. Kirkee (Pune)\r\n"
                + "B. Mhow\r\n"
                + "C. Dehradun\r\n"
                + "D. Chennai','A'),"
                + "('The number of already named bones in the human skeleton is\r\n"
                + "A. 200\r\n"
                + "B. 206\r\n"
                + "C. 212\r\n"
                + "D. 218','B'),"
                + "('First satellite of India is named after\r\n"
                + "A. Aryabhatta\r\n"
                + "B. Bhaskara II\r\n"
                + "C. Bhaskara I\r\n"
                + "D. Albert Einstein','A'),"
                + "('First atomic reactor of India was\r\n"
                + "A. Zerlina\r\n"
                + "B. Dhruva\r\n"
                + "C. Apsara\r\n"
                + "D. Kamini','C'),"
                + "('First atomic power station of India was set up at\r\n"
                + "A. Surat (Gujarat)\r\n"
                + "B. Tarapur (Maharashtra)\r\n"
                + "C. Trombay (Maharashtra)\r\n"
                + "D. Solapur (Maharashtra)','B'),"
                + "('For purifying drinking water alum is used\r\n"
                + "A. for coagulation of mud particles\r\n"
                + "B. to kill bacteria\r\n"
                + "C. to remove salts\r\n"
                + "D. to remove gases','A'),"
                + "('Which planet is known as the Red Planet?\r\n"
                + "A. Venus\r\n"
                + "B. Mars\r\n"
                + "C. Jupiter\r\n"
                + "D. Saturn', 'B'),"
                + "('What is the capital of France?\r\n"
                + "A. London\r\n"
                + "B. Berlin\r\n"
                + "C. Madrid\r\n"
                + "D. Paris', 'D'),"
                + "('What is the chemical symbol for gold?\r\n"
                + "A. Go\r\n"
                + "B. Gl\r\n"
                + "C. Au\r\n"
                + "D. Ag','C'),"
                + "('Which is the largest state in India by area?\r\n"
                + "A. Maharashtra\r\n"
                + "B. Madhya Pradesh\r\n"
                + "C. Rajasthan\r\n"
                + "D. Uttar Pradesh', 'C'),"
                + "('What is the national flower of India?\r\n"
                + " A. Rose\r\n"
                + " B. Lotus\r\n"
                + " C. Tulip\r\n"
                + " D. Marigold','B'),"
                + "('Which river is known as the [Sorrow of Bengal]?\r\n"
                + " A. Brahmaputra\r\n"
                + " B. Yamuna\r\n"
                + " C. Ganges\r\n"
                + " D. Godavari','A'),"
                + "('Who was the first Prime Minister of India?\r\n"
                + " A. Sardar Patel\r\n"
                + " B. Jawaharlal Nehru\r\n"
                + " C. Mahatma Gandhi\r\n"
                + " D. Subhas Chandra Bose','B'),"
                + "('In which state is the city of Jaipur located?\r\n"
                + " A. Madhya Pradesh\r\n"
                + " B. Rajasthan\r\n"
                + " C. Haryana\r\n"
                + " D. Punjab','B'),"
                + "('What is the currency of India?\r\n"
                + " A. Rupee\r\n"
                + " B. Taka\r\n"
                + " C. Rupiah\r\n"
                + " D. Ringgit','A'),"
                + "('Who is known as the [Father of the Nation] in India?\r\n"
                + " A. Sardar Patel\r\n"
                + " B. Jawaharlal Nehru\r\n"
                + " C. Mahatma Gandhi\r\n"
                + " D. Subhas Chandra Bose','C'),"
                + "('What is the official language of India?\r\n"
                + " A. English\r\n"
                + " B. Hindi\r\n"
                + " C. Bengali\r\n"
                + " D. Tamil','B'),"
                + "('The famous monument [Taj Mahal] is located in which city?\r\n"
                + " A. Delhi\r\n"
                + " B. Mumbai\r\n"
                + " C. Agra\r\n"
                + " D. Jaipur','C'),"
                + "('Who wrote the Indian national anthem, [Jana Gana Mana]?\r\n"
                + " A. Rabindranath Tagore\r\n"
                + " B. Mahatma Gandhi\r\n"
                + " C. Jawaharlal Nehru\r\n"
                + " D. Sardar Patel','A'),"
                + "('Which Indian state is known as the [Land of Five Rivers]?\r\n"
                + " A. Punjab\r\n"
                + " B. Haryana\r\n"
                + " C. Uttar Pradesh\r\n"
                + " D. Bihar','A'),"
                + "('In which year did India gain independence from British rule?\r\n"
                + " A. 1942\r\n"
                + " B. 1947\r\n"
                + " C. 1950\r\n"
                + " D. 1955','B'),"
                + "('What is the highest civilian award in India?\r\n"
                + " A. Param Vir Chakra\r\n"
                + " B. Padma Shri\r\n"
                + " C. Bharat Ratna\r\n"
                + " D. Kirti Chakra','C'),"
                + "('Which Indian festival is known as the [Festival of Lights]?\r\n"
                + " A. Holi\r\n"
                + " B. Diwali\r\n"
                + " C. Eid\r\n"
                + " D. Navratri','B'),"
                + "('Which Indian state is known as the [Land of Temples]?\r\n"
                + " A. Gujarat\r\n"
                + " B. Rajasthan\r\n"
                + " C. Tamil Nadu\r\n"
                + " D. Odisha','C'),"
                + "('What is the national animal of India?\n"
                + " A. Lion\r\n"
                + " B. Tiger\r\n"
                + " C. Elephant\r\n"
                + " D. Leopard','B')";
        Connection con = ConnectionDetail.getConnectionDetails();
        Statement statement = con.createStatement();
        statement.execute(sql);
        statement.close();
        con.close();
    }
}