package com.quiz;

public class InsertQuestions {
	public String getInsertQuestions() {
		String sql="insert into mcq(Questions,Answer)values"
				+ "('Modern Indo-Aryan languages are based on an ancient language called\r\n"
				+ "A. Hindi\r\n"
				+ "B. Sanskrit\r\n"
				+ "C. Kannada\r\n"
				+ "D.Tamil','B'),"
				+ "('The Central Command of Army is located at\r\n"
				+ "A. Pune\r\n"
				+ "B. Udhampur\r\n"
				+ "C. Lucknow\r\n"
				+ "D. Mhow','C'),"
				+ "('The department of Atomic Energy was established in\r\n"
				+ "A. 1948\r\n"
				+ "B. 1954\r\n"
				+ "C. 1963\r\n"
				+ "D. 1971','B'),"
				+ "('The blood pressure of a young male human being is\r\n"
				+ "A. 110/70\r\n"
				+ "B. 120/80\r\n"
				+ "C. 135/90\r\n"
				+ "D. 140/100','B'),"
				+ "('The college of Military Engineering is situated at\r\n"
				+ "A. Kirkee (Pune)\r\n"
				+ "B. Mhow\r\n"
				+ "C. Dehradun\r\n"
				+ "D. Chennai','A'),"
				+ "('The number of already named bones in the human skeleton is\r\n"
				+ "A. 200\r\n"
				+ "B. 206\r\n"
				+ "C. 212\r\n"
				+ "D. 218','B'),"
				+ "('First satellite of India is named after\r\n"
				+ "A. Aryabhatta\r\n"
				+ "B. Bhaskara II\r\n"
				+ "C. Bhaskara I\r\n"
				+ "D. Albert Einstein','A'),"
				+ "('First atomic reactor of India was\r\n"
				+ "A. Zerlina\r\n"
				+ "B. Dhruva\r\n"
				+ "C. Apsara\r\n"
				+ "D. Kamini','C'),"
				+ "('First atomic power station of India was set up at\r\n"
				+ "A. Surat (Gujarat)\r\n"
				+ "B. Tarapur (Maharashtra)\r\n"
				+ "C. Trombay (Maharashtra)\r\n"
				+ "D. Solapur (Maharashtra)','B'),"
				+ "('For purifying drinking water alum is used\r\n"
				+ "A. for coagulation of mud particles\r\n"
				+ "B. to kill bacteria\r\n"
				+ "C. to remove salts\r\n"
				+ "D. to remove gases','A')";
		return sql;
	}
}